apiVersion: v1
kind: Service
metadata:
  name: fastapi-rest-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app.kubernetes.io/name: fastapi-rest
